version: "3.8"

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - mynetwork

  backend:
    build: ./src
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      OLLAMA_URL: http://ollama:11434/
    depends_on:
      ollama:
        condition: service_started
    networks:
      - mynetwork
    entrypoint: >
      sh -c "
      echo 'Aguardando Ollama...';
      until curl -s http://ollama:11434/api/tags; do sleep 5; done;
      echo 'Iniciando backend...';
      exec uvicorn server:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build: ./web
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - mynetwork

volumes:
  ollama_data:

networks:
  mynetwork:
